//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKSupply.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HKSupplyRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HKSupplyRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HKSupply.Resources.HKSupplyRes", typeof(HKSupplyRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Billing Address.
        /// </summary>
        internal static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caliber.
        /// </summary>
        internal static string Caliber {
            get {
                return ResourceManager.GetString("Caliber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This is not a valid value for this column.
        /// </summary>
        internal static string CellDataError {
            get {
                return ResourceManager.GetString("CellDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color 1.
        /// </summary>
        internal static string Color1 {
            get {
                return ResourceManager.GetString("Color1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color 2.
        /// </summary>
        internal static string Color2 {
            get {
                return ResourceManager.GetString("Color2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact Name.
        /// </summary>
        internal static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact Phone.
        /// </summary>
        internal static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Date.
        /// </summary>
        internal static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Currency 1.
        /// </summary>
        internal static string Currency1 {
            get {
                return ResourceManager.GetString("Currency1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Currency 2.
        /// </summary>
        internal static string Currency2 {
            get {
                return ResourceManager.GetString("Currency2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer Name.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Base.
        /// </summary>
        internal static string DataBase {
            get {
                return ResourceManager.GetString("DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DB Server.
        /// </summary>
        internal static string DbServer {
            get {
                return ResourceManager.GetString("DbServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database Server Connection Error.
        /// </summary>
        internal static string DBServerConnectionError {
            get {
                return ResourceManager.GetString("DBServerConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default Supplier.
        /// </summary>
        internal static string DefaultSupplier {
            get {
                return ResourceManager.GetString("DefaultSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description (Chinese).
        /// </summary>
        internal static string DescriptionChinese {
            get {
                return ResourceManager.GetString("DescriptionChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doc Type.
        /// </summary>
        internal static string DocType {
            get {
                return ResourceManager.GetString("DocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exchange Rate Used.
        /// </summary>
        internal static string ExchangeRateUsed {
            get {
                return ResourceManager.GetString("ExchangeRateUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Family HK.
        /// </summary>
        internal static string FamilyHk {
            get {
                return ResourceManager.GetString("FamilyHk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This field is required.
        /// </summary>
        internal static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File doesn&apos;t exist.
        /// </summary>
        internal static string FileDoesntExist {
            get {
                return ResourceManager.GetString("FileDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File Name.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Form not found.
        /// </summary>
        internal static string FormNotFound {
            get {
                return ResourceManager.GetString("FormNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Functionality Already Exist.
        /// </summary>
        internal static string FunctionalityAlreadyExist {
            get {
                return ResourceManager.GetString("FunctionalityAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Functionality-Role Already Exist.
        /// </summary>
        internal static string FunctionalityRoleAlreadyExist {
            get {
                return ResourceManager.GetString("FunctionalityRoleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hw Type L1.
        /// </summary>
        internal static string HwTypeL1 {
            get {
                return ResourceManager.GetString("HwTypeL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hw Type L2.
        /// </summary>
        internal static string HwTypeL2 {
            get {
                return ResourceManager.GetString("HwTypeL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hw Type L3.
        /// </summary>
        internal static string HwTypeL3 {
            get {
                return ResourceManager.GetString("HwTypeL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Customer.
        /// </summary>
        internal static string IdCustomer {
            get {
                return ResourceManager.GetString("IdCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Family HK.
        /// </summary>
        internal static string IdFamilyHk {
            get {
                return ResourceManager.GetString("IdFamilyHk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Incoterm.
        /// </summary>
        internal static string IdIncoterm {
            get {
                return ResourceManager.GetString("IdIncoterm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Model.
        /// </summary>
        internal static string IdModel {
            get {
                return ResourceManager.GetString("IdModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Payment Terms.
        /// </summary>
        internal static string IdPaymentTerms {
            get {
                return ResourceManager.GetString("IdPaymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Prototype.
        /// </summary>
        internal static string IdPrototype {
            get {
                return ResourceManager.GetString("IdPrototype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id Supplier.
        /// </summary>
        internal static string IdSupplier {
            get {
                return ResourceManager.GetString("IdSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incoterm.
        /// </summary>
        internal static string Incoterm {
            get {
                return ResourceManager.GetString("Incoterm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incr Lot.
        /// </summary>
        internal static string IncrLot {
            get {
                return ResourceManager.GetString("IncrLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid ID.
        /// </summary>
        internal static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid login.
        /// </summary>
        internal static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Password.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid user.
        /// </summary>
        internal static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item BCN.
        /// </summary>
        internal static string ItemBCN {
            get {
                return ResourceManager.GetString("ItemBCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item Description.
        /// </summary>
        internal static string ItemDescription {
            get {
                return ResourceManager.GetString("ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item HK.
        /// </summary>
        internal static string ItemHK {
            get {
                return ResourceManager.GetString("ItemHK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item Subver.
        /// </summary>
        internal static string ItemSubver {
            get {
                return ResourceManager.GetString("ItemSubver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Item Ver.
        /// </summary>
        internal static string ItemVer {
            get {
                return ResourceManager.GetString("ItemVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Launch Date.
        /// </summary>
        internal static string LaunchDate {
            get {
                return ResourceManager.GetString("LaunchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lead Time.
        /// </summary>
        internal static string LeadTime {
            get {
                return ResourceManager.GetString("LeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login mandatory.
        /// </summary>
        internal static string LoginMandatory {
            get {
                return ResourceManager.GetString("LoginMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material L1.
        /// </summary>
        internal static string MaterialL1 {
            get {
                return ResourceManager.GetString("MaterialL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material L2.
        /// </summary>
        internal static string MaterialL2 {
            get {
                return ResourceManager.GetString("MaterialL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material L3.
        /// </summary>
        internal static string MaterialL3 {
            get {
                return ResourceManager.GetString("MaterialL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mat Type L1.
        /// </summary>
        internal static string MatTypeL1 {
            get {
                return ResourceManager.GetString("MatTypeL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mat Type L2.
        /// </summary>
        internal static string MatTypeL2 {
            get {
                return ResourceManager.GetString("MatTypeL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mat Type L3.
        /// </summary>
        internal static string MatTypeL3 {
            get {
                return ResourceManager.GetString("MatTypeL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Min Lot.
        /// </summary>
        internal static string MinLot {
            get {
                return ResourceManager.GetString("MinLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password Mandatory.
        /// </summary>
        internal static string NewPasswordMandatory {
            get {
                return ResourceManager.GetString("NewPasswordMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No customer selected.
        /// </summary>
        internal static string NoCustomerSelected {
            get {
                return ResourceManager.GetString("NoCustomerSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No data selected.
        /// </summary>
        internal static string NoDataSelected {
            get {
                return ResourceManager.GetString("NoDataSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No file selected.
        /// </summary>
        internal static string NoFileSelected {
            get {
                return ResourceManager.GetString("NoFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Functionality Exist.
        /// </summary>
        internal static string NoFunctionalityExist {
            get {
                return ResourceManager.GetString("NoFunctionalityExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Functionality-Role Exist.
        /// </summary>
        internal static string NoFunctionalityRoleExist {
            get {
                return ResourceManager.GetString("NoFunctionalityRoleExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No pending changes.
        /// </summary>
        internal static string NoPendingChanges {
            get {
                return ResourceManager.GetString("NoPendingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Role Exist.
        /// </summary>
        internal static string NoRoleExist {
            get {
                return ResourceManager.GetString("NoRoleExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Role Exist.
        /// </summary>
        internal static string NoStoreExist {
            get {
                return ResourceManager.GetString("NoStoreExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} can&apos;t be null.
        /// </summary>
        internal static string NullArgument {
            get {
                return ResourceManager.GetString("NullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Old Password.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect Old Password.
        /// </summary>
        internal static string OldPasswordError {
            get {
                return ResourceManager.GetString("OldPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Old Password Mandatory.
        /// </summary>
        internal static string OldPasswordMandatory {
            get {
                return ResourceManager.GetString("OldPasswordMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to open the file?.
        /// </summary>
        internal static string OpenFileQuestion {
            get {
                return ResourceManager.GetString("OpenFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password changed successfully.
        /// </summary>
        internal static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password mandatory.
        /// </summary>
        internal static string PasswordMandatory {
            get {
                return ResourceManager.GetString("PasswordMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Terms.
        /// </summary>
        internal static string PaymentTerms {
            get {
                return ResourceManager.GetString("PaymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Photo.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price Base Currency.
        /// </summary>
        internal static string PriceBaseCurrency {
            get {
                return ResourceManager.GetString("PriceBaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prototype Description.
        /// </summary>
        internal static string PrototypeDescription {
            get {
                return ResourceManager.GetString("PrototypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prototype Name.
        /// </summary>
        internal static string PrototypeName {
            get {
                return ResourceManager.GetString("PrototypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prototype Status.
        /// </summary>
        internal static string PrototypeStatus {
            get {
                return ResourceManager.GetString("PrototypeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ratio.
        /// </summary>
        internal static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removal Date.
        /// </summary>
        internal static string RemovalDate {
            get {
                return ResourceManager.GetString("RemovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat Password.
        /// </summary>
        internal static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat Password Incorrect.
        /// </summary>
        internal static string RepeatPasswordError {
            get {
                return ResourceManager.GetString("RepeatPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat Password Mandatory.
        /// </summary>
        internal static string RepeatPasswordMandatory {
            get {
                return ResourceManager.GetString("RepeatPasswordMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset Password.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role Already Exist.
        /// </summary>
        internal static string RoleAlreadyExist {
            get {
                return ResourceManager.GetString("RoleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save changes?.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Successfully.
        /// </summary>
        internal static string SaveSuccessfully {
            get {
                return ResourceManager.GetString("SaveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scrap.
        /// </summary>
        internal static string Scrap {
            get {
                return ResourceManager.GetString("Scrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segment.
        /// </summary>
        internal static string Segment {
            get {
                return ResourceManager.GetString("Segment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select doc type.
        /// </summary>
        internal static string SelectDocType {
            get {
                return ResourceManager.GetString("SelectDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shipping Address.
        /// </summary>
        internal static string ShippingAddress {
            get {
                return ResourceManager.GetString("ShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign in.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status Cial.
        /// </summary>
        internal static string StatusCial {
            get {
                return ResourceManager.GetString("StatusCial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status Prod.
        /// </summary>
        internal static string StatusProd {
            get {
                return ResourceManager.GetString("StatusProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Store Already Exist.
        /// </summary>
        internal static string StoreAlreadyExist {
            get {
                return ResourceManager.GetString("StoreAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supplier.
        /// </summary>
        internal static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supplier Name.
        /// </summary>
        internal static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VAT Number.
        /// </summary>
        internal static string VATNumber {
            get {
                return ResourceManager.GetString("VATNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View Item price list.
        /// </summary>
        internal static string ViewItemPriceList {
            get {
                return ResourceManager.GetString("ViewItemPriceList", resourceCulture);
            }
        }
    }
}
