SELECT DISTINCT        
	T0.ItemCode
	,T0.ItemName
	,T0.U_ETN_MODEL
	,T0.U_OPN_CATSUP
	,T0.ItmsGrpCod
	,T0.U_ETN_TIPART
	,T1.[Name] as TipArtDesc
	,T0.U_ETN_ETN_SUBTIPART
	,T0.U_OPN_CAT
FROM  OITM T0 WITH (NOLOCK)
LEFT JOIN [@ETN_TIPART] T1 WITH (NOLOCK) ON T1.Code = T0.U_ETN_TIPART
WHERE  T0.ItmsGrpCod in (131,132,133,134)
ORDER BY T0.ItmsGrpCod, ItemCode