SELECT DISTINCT        
	T2.ItemCode
	,T2.ItemName
	,T2.U_ETN_MODEL
	,T2.U_OPN_CATSUP
	,T2.ItmsGrpCod
	,T2.U_ETN_TIPART
	,T3.[Name] as TipArtDesc
	,T2.U_ETN_ETN_SUBTIPART
	,T2.U_OPN_CAT
FROM ETN_BOM_HEAD AS T0 WITH (NOLOCK)
INNER JOIN ETN_BOM_LINES AS T1 WITH (NOLOCK) ON T1.CodeBom = T0.Code
INNER JOIN OITM T2 WITH (NOLOCK) ON T2.ItemCode = T1.ItemCode
LEFT JOIN [@ETN_TIPART] T3 WITH (NOLOCK) ON T3.Code = T2.U_ETN_TIPART
WHERE        
	T0.ItemCode = @item
