// <auto-generated />
namespace HKSupply.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class detailBomHw_scrap_20170530_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(detailBomHw_scrap_20170530_01));
        
        string IMigrationMetadata.Id
        {
            get { return "201705301036149_detailBomHw_scrap_20170530_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
