// <auto-generated />
namespace HKSupply.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PricesList_precision_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PricesList_precision_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201704190958289_PricesList_precision_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
