// <auto-generated />
namespace HKSupply.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IdItemBcn_IdItemHk_changeLength_011 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdItemBcn_IdItemHk_changeLength_011));
        
        string IMigrationMetadata.Id
        {
            get { return "201705031357142_IdItemBcn_IdItemHk_changeLength_01.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
