// <auto-generated />
namespace HKSupply.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ColorModelStatusCial_DefincionCampos_22 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ColorModelStatusCial_DefincionCampos_22));
        
        string IMigrationMetadata.Id
        {
            get { return "201704111033353_ColorModelStatusCial_DefincionCampos_2.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
