// <auto-generated />
namespace HKSupply.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class items_20170426_03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(items_20170426_03));
        
        string IMigrationMetadata.Id
        {
            get { return "201704260740393_items_20170426_03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
