// <auto-generated />
namespace HKSupply.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BomBreakdown_20170616_02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BomBreakdown_20170616_02));
        
        string IMigrationMetadata.Id
        {
            get { return "201706160759192_BomBreakdown_20170616_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
