// <auto-generated />
namespace HKSupply.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class itemHwMt_idmodel_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(itemHwMt_idmodel_01));
        
        string IMigrationMetadata.Id
        {
            get { return "201705020858436_itemHwMt_idmodel_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
